# -*- coding: utf-8 -*-
"""salary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1igOOhVDEzg_F6BHOxa8YBjwPTgdN0Rzh
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/sample_data/salary_data.csv')
df.head(10)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 6))
sns.scatterplot(x='YearsExperience', y='Salary', data=df)
plt.title('Years of Experience vs Salary')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.grid(True)
plt.show()

"""### Fit Linear Regression Model"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Define features (X) and target (y)
X = df[['YearsExperience']]
y = df['Salary']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(f"Training set size: {len(X_train)} samples")
print(f"Test set size: {len(X_test)} samples")

# Initialize and train the Linear Regression model
model = LinearRegression()
model.fit(X_train, y_train)

print(f"Model Intercept: {model.intercept_:.2f}")
print(f"Model Coefficient (YearsExperience): {model.coef_[0]:.2f}")

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
mae = mean_absolute_error(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)
r2 = r2_score(y_test, y_pred)

print(f"Mean Absolute Error (MAE): {mae:.2f}")
print(f"Mean Squared Error (MSE): {mse:.2f}")
print(f"Root Mean Squared Error (RMSE): {rmse:.2f}")
print(f"R-squared (R2): {r2:.2f}")

# Visualize the regression line
plt.figure(figsize=(10, 6))
sns.scatterplot(x='YearsExperience', y='Salary', data=df, label='Actual Data')
plt.plot(X_test, y_pred, color='red', linewidth=2, label='Regression Line')
plt.title('Linear Regression: Years of Experience vs Salary')
plt.xlabel('Years of Experience')
plt.ylabel('Salary')
plt.grid(True)
plt.legend()
plt.show()

"""### Predict Salary based on Years of Experience"""

import ipywidgets as widgets
from IPython.display import display

# Create an input text box for years of experience
experience_input = widgets.FloatText(
    value=5.0,
    description='Years Experience:',
    disabled=False
)

# Create an output widget to display the prediction
output = widgets.Output()

# Function to perform prediction and display output
def predict_salary(experience):
    with output:
        output.clear_output()
        if experience is not None and experience >= 0:
            # Convert the input to the format expected by the model
            experience_df = pd.DataFrame([experience], columns=['YearsExperience'])
            predicted_salary = model.predict(experience_df)[0]
            print(f"Predicted Salary for {experience:.1f} years of experience: ${predicted_salary:,.2f}")
        else:
            print("Please enter a valid number of years experience.")

# Link the input widget to the prediction function
widgets.interactive_output(predict_salary, {'experience': experience_input})

# Display the input widget and output area
display(experience_input, output)

import pickle

# Save the trained model to a .pkl file
model_filename = 'linear_regression_model.pkl'
with open(model_filename, 'wb') as file:
    pickle.dump(model, file)

print(f"Model successfully saved to {model_filename}")